services:
  # Next.js web app (standalone)
  web-prod:
    container_name: nextjs-directus-web-prod
    build:
      context: .
      dockerfile: ./docker/Dockerfile.web.build-time.prod
      args:
        - NODE_ENV=production
        - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL:-http://localhost:8055}
        - NEXT_PUBLIC_APP_URL=${NEXT_PUBLIC_APP_URL:-http://localhost:3000}
        - AUTH_SECRET=${AUTH_SECRET:-QgafJQw3O/k1gambz7YGKjtj5ZZe0dnL/WlSw4PtMDc=}
        - API_ADMIN_TOKEN=${API_ADMIN_TOKEN:-secret-admin-token}
        - API_PING_PATH=${API_PING_PATH:-/server/health}
        - SKIP_STATIC_GENERATION=true
    restart: unless-stopped
    network_mode: host
    environment:
      - NODE_ENV=production
      - API_PING_PATH=/server/health
      # Server-side API URL (direct localhost access via host networking)
      - API_URL=http://localhost:${NEXT_PUBLIC_API_PORT:-8055}
      # Client-side API URL (localhost for browser)
      - NEXT_PUBLIC_API_URL=http://localhost:${NEXT_PUBLIC_API_PORT:-8055}
      - NEXT_PUBLIC_API_PORT=${NEXT_PUBLIC_API_PORT:-8055}
      - NEXT_PUBLIC_APP_URL=${NEXT_PUBLIC_APP_URL:-http://localhost:3000}
      - NEXT_PUBLIC_APP_PORT=${NEXT_PUBLIC_APP_PORT:-3000}
      - API_ADMIN_TOKEN=${API_ADMIN_TOKEN:-secret-admin-token}
      - AUTH_SECRET=${AUTH_SECRET:-QgafJQw3O/k1gambz7YGKjtj5ZZe0dnL/WlSw4PtMDc=}
    # Remove networks section to use default bridge network for external connectivity
    # This allows the container to connect to any external API server
